version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    networks:
      - food_app-network
    

  database:
    build: ./database
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - food_app-network
    environment:
      MYSQL_ROOT_PASSWORD: ""
    

  frontend:
    build: ./frontend
    ports:
      - "5500:80"
    depends_on:
      - database
    networks:
      - food_app-network

networks:
  food_app-network:
    external: true
